services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${APPDATA_ROOT}/plex:/config
      - ${MEDIA_ROOT}/tv:/tv
      - ${MEDIA_ROOT}/movies:/movies

    restart: unless-stopped
